# Generated by Django 5.2.5 on 2025-08-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualization',
            name='css',
            field=models.CharField(blank=True, choices=[('ui/app/css/index.css', 'ui/app/css/index.css'), ('ui/app/css/base.css', 'ui/app/css/base.css')], help_text='template path of e.g. index.css', max_length=2000, null=True),
        ),
    ]
