# Generated by Django 5.2.5 on 2025-08-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_alter_visualization_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualization',
            name='template',
            field=models.CharField(blank=True, choices=[('ui/app/templates/Map.html', 'ui/app/templates/Map.html'), ('ui/app/templates/basic.html', 'ui/app/templates/basic.html'), ('ui/app/templates/MainMap.html', 'ui/app/templates/MainMap.html'), ('ui/app/templates/vue.html', 'ui/app/templates/vue.html')], help_text='template path of e.g. index.html that will be loaded first', max_length=2000, null=True),
        ),
    ]
