# Generated by Django 5.2.5 on 2025-08-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_alter_visualization_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualization',
            name='vueData',
            field=models.CharField(blank=True, choices=[('ui/app/data/user.js.vue', 'ui/app/data/user.js.vue'), ('ui/app/data/geojson_layers.leaflet.js', 'ui/app/data/geojson_layers.leaflet.js')], help_text="template path or string if 'render_sting' includes key 'vueData'", max_length=2000, null=True),
        ),
    ]
