# Generated by Django 5.2.5 on 2025-08-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0007_alter_visualization_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualization',
            name='template',
            field=models.CharField(blank=True, choices=[('ui/app/templates/Map.html', 'ui/app/templates/Map.html'), ('ui/app/templates/openLayers.html', 'ui/app/templates/openLayers.html'), ('ui/app/templates/MapOriginal.html', 'ui/app/templates/MapOriginal.html'), ('ui/app/templates/foliumMap.html', 'ui/app/templates/foliumMap.html'), ('ui/app/templates/vueMap.html', 'ui/app/templates/vueMap.html'), ('ui/app/templates/basic.html', 'ui/app/templates/basic.html'), ('ui/app/templates/MainMap.html', 'ui/app/templates/MainMap.html'), ('ui/app/templates/htmx.html', 'ui/app/templates/htmx.html'), ('ui/app/templates/generic.html', 'ui/app/templates/generic.html'), ('ui/app/templates/openLayersSlim.html', 'ui/app/templates/openLayersSlim.html'), ('ui/app/templates/vue.html', 'ui/app/templates/vue.html')], help_text='template path of e.g. index.html that will be loaded first', max_length=2000, null=True),
        ),
    ]
