"""
Django settings for wqdms project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path
from os import getenv
from corsheaders.defaults import default_methods

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
SERVER_HOST = getenv("SERVER_HOST", "http://localhost:8000")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure--af3_fl2ti+dmfgz0_n09*xbam9#@tt6h1as0yj6$2b_+vq2^i"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
TESTING = False  # "test" in sys.argv or "PYTEST_VERSION" in os.environ
ALLOWED_HOSTS = ["*"]
CORS_ALLOW_METHODS = (
    *default_methods,
    "POKE",
)
CORS_ALLOW_ALL_ORIGINS = True

CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1",
    "http://0.0.0.0",
    "http://localhost",
    "http://127.0.0.1:8081",
    "http://0.0.0.0:8081",
    "http://localhost:8081",
    "http://127.0.0.1:8080",
    "http://0.0.0.0:8080",
    "http://localhost:8080",
    SERVER_HOST,
]
INTERNAL_IPS = [
    "127.0.0.1",
]
# Application definition


INSTALLED_APPS = [
    "corsheaders",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.gis",
    "django_filters",
    "rest_framework",
    "rest_framework_gis",
    "drf_spectacular",
    "drf_spectacular_sidecar",  # required for Django collectstatic
    "django_extensions",
    "sensorthings",
    "waterquality",
    "interface",
    "interactive",
    "api",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "wqdms.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            # BASE_DIR / "static",
            BASE_DIR / "interface/templates",
            BASE_DIR / "api/templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "wqdms.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
SENSORTHINGS_DATABASE = {
    "ENGINE": "django.db.backends.postgresql",
    "NAME": getenv("POSTGRES_DB", "sensorthings"),
    "USER": getenv("POSTGRES_USER", "sensorthings"),
    "PASSWORD": getenv("POSTGRES_PASSWORD", "admin1234"),
    "HOST": getenv("POSTGRES_HOST", "localhost"),
    "PORT": getenv("POSTGRES_PORT", "5432"),
}

DATABASES = {
    "default": {
        # "ENGINE": "django.db.backends.sqlite3",
        "ENGINE": "django.contrib.gis.db.backends.spatialite",
        "NAME": BASE_DIR / "db.sqlite3",
    },
    "sensorthings": SENSORTHINGS_DATABASE,
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "static"
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"
STATICFILES_DIRS = [
    BASE_DIR / "interface/templates",
    BASE_DIR / "api/templates",
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

SPECTACULAR_SETTINGS = {
    "REDOC_DIST": "SIDECAR",
    "REDOC_UI_SETTINGS": {
        "downloadDefinitionUrl": "/api/v0/schema/",
    },
    "OAS_VERSION": "3.0.3",
    "TITLE": "Your Project API",
    "DESCRIPTION": "Water Quality Data Management System",
    "VERSION": "0.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SWAGGER_UI_DIST": "SIDECAR",  # shorthand to use the sidecar instead
    "SWAGGER_UI_FAVICON_HREF": "SIDECAR",
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "persistAuthorization": True,
        "displayOperationId": True,
        "url": "/api/v0/schema",
    },
}

SWAGGER_SETTINGS = {
    "LOGIN_URL": "rest_framework:login",
    "LOGOUT_URL": "rest_framework:logout",
}

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}


NOTEBOOK_ARGUMENTS = [
    "--ip",
    "0.0.0.0",
    "--port",
    "8002",
    "--autoreload",
    "--allow-root",
    "--ServerApp.token=admin1234",
    "--NotebookApp.default_url=/lab",
    "--no-browser",
    "--JupyterHub.bind_url='http://localhost:8002'",
    # "--ServerApp.base_url=/lab",
    # "--Spawner.default_url=/lab",
    # "--ServerApp.default_url=/lab",
    # "--ServerApp.port=8002",
]
# REST
# REST_FRAMEWORK = {
#     "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
#     "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
#     "PAGE_SIZE": 1,
#     "DEFAULT_RENDERER_CLASSES": [
#         "rest_framework.renderers.JSONRenderer",
#         "rest_framework.renderers.BrowsableAPIRenderer",
#     ],
#     "DEFAULT_AUTHENTICATION_CLASSES": (
#         "rest_framework_simplejwt.authentication.JWTAuthentication",
#         "rest_framework.authentication.BasicAuthentication",
#         "rest_framework.authentication.SessionAuthentication",
#     ),
# }
