# Generated by Django 5.2.5 on 2025-08-21 21:19

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterquality', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterbody',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryCollectionField(blank=True, null=True, srid=4326),
        ),
    ]
